### ISSUE TITLE
PySLSQP on Windows 11

### ISSUE THREAD

**Issue by antonionicampos** [anugrahjo/PySLSQP#2]
I managed to install PySLSQP on Windows 11 successfully. However, when I try to perform an optimization, the following error appears.

```
Traceback (most recent call last):
  File "C:\git\slsqp\himmelblau.py", line 24, in <module>
    from pyslsqp import optimize
  File "c:\git\slsqp\.venv\lib\site-packages\pyslsqp\__init__.py", line 3, in <module>
    from pyslsqp.main import optimize, get_default_options
  File "c:\git\slsqp\.venv\lib\site-packages\pyslsqp\main.py", line 28, in <module>
    from pyslsqp._slsqp import slsqp
ModuleNotFoundError: No module named 'pyslsqp._slsqp'
```

- Running in Python 3.10.11 
- Compiled in gcc 11.4.0

**Comment by antonionicampos** [comment]
I solved it by taking the files from the PySLSQP folder /pyslsqp/slsqp, compiling them using numpy.f2py using the following command.

```
python -m numpy.f2py -c slsqp.pyf slsqp_optmz.f
```
And copying/pasting the generated files with the .pyd and .dll extensions to the PySLSQP module folder installed in my Python virtual environment.

Would it be possible to include these steps, for Windows users, in the package build during installation?

**Comment by anugrahjo** [comment]
Thanks for letting me know! Could you share your directory structure after you fixed the issue? I can include the copying of the files in the package build and add a test for Windows installation.

**Comment by antonionicampos** [comment]
I don't know if I did it the best way possible, but I copied the repository files that are in the pyslsqp/slsqp folder into my working folder, inside a folder that I called slsqp, and ran the numpy.f2py command to compile the fortran algorithm.

![screen1](https://github.com/user-attachments/assets/2e2659f8-e5c0-4951-864b-8024c6e27f46)

Two files were created:
- _slsqp.cp310-win_amd64.pyd
- _slsqp\.libs\libslsqp_op.Z5DVG7WSPM3BUBWF7FLRJL4D22LX6RL4.gfortran-win_amd64.dll

![screen2](https://github.com/user-attachments/assets/6b8b11a7-ff3e-402e-ba0b-4ef97a801750)

Finally, I inserted these two files into the package folder in my virtual environment.

![screen3](https://github.com/user-attachments/assets/c1bf8c3a-582d-410f-aff2-085930239c74)

**Comment by anugrahjo** [comment]
Thanks a lot for the detailed explanation! It seemed like the compiled file generated for Windows by the meson workflow in the repository was corrupted for some reason. It is fixed with the latest release on PyPI. 

Additionally, I have also made Windows wheels available on PyPI for common platforms so that users don't have to compile the package manually as they had to in the previous version. `pip install pyslsqp` should now install _pyslsqp_ for most Windows platforms without any local compilation.

**Comment by antonionicampos** [comment]
Thank you @anugrahjo! Excellent work on the package.

**Comment by anugrahjo** [comment]
You're welcome @antonionicampos! I'm glad you found the package helpful. Let me know if you have any other feedback.
